USE db24
DEMITER $$
CREATE TRIGGER MyTBL_0a gaurd1 BEFORE INSERT ON MyTBL_0a
FOR EACH ROW
BEGIN
DECLARE a varchure(100);
SELECT CURRENT_USER() INTO @a;
SIGNAL SQLSTATE '50000''SET massage_text=@a;
END$$
DELIMITER;
ISERT INTO MyTBL_0a(Title) VALUE('AAA'); */ 

